### ISSUE TITLE
其实不用drop掉SSDT也可以用hotpatch方法定制USB的

### ISSUE THREAD

**Issue by Teacher-c** [daliansky/OC-little#18]
我的机型原始GUPC方法为：

```Swift
Method (GUPC, 1, Serialized)
        {
            Name (PCKG, Package (0x04)
            {
                Zero, 
                0xFF, 
                Zero, 
                Zero
            })
            PCKG [Zero] = Arg0
            Return (PCKG)
        }
```

然后任一端口的_UPC Method均调用序列化GUPC方法：

```Swift
Method (_UPC, 0, NotSerialized) 
        {
            Return (GUPC(One)) 
        }
```
或
```Swift
Method (_UPC, 0, NotSerialized) 
        {
            Return (GUPC(Zero)) 
        }
```

可以看出问题在于把所有的端口都内建了，GUPC函数又只有一个参数用于定义端口存在（One）或被屏蔽（Zero）

故我的处理如下，hotpatch重命名GUPC为XUPC，然后在自定义SSDT重写该方法：

```Swift
        Name (USBP, Zero)
        Method (GUPC, 1, Serialized)
        {
            Name (PCKG, Package (0x04)
            {
                0xFF, 
                0x03, 
                Zero, 
                Zero
            })
            USBP += One
            If (((USBP == 0x04) || (Arg0 == Zero)))
            {
                PCKG [Zero] = Zero
            }

            If ((((USBP == 0x04) || (USBP == 0x05)) || (USBP == 0x06)))
            {
                PCKG [One] = 0xFF
            }

            Return (PCKG) 
        }
```

因为GUPC方法是序列化的，而且每个USB端口（从HS01到HS10，以及USR1，USR2，SS01到SS06，）均会调用一次，所以定义了USBP并且通过自增实现了端口的一一对应。
本人主要实现了：修正端口连接类型（HS04，HS05，HS06分别为内建指纹识别，相机，蓝牙），并且屏蔽HS04端口。

**Comment by williambj1** [comment]
@Teacher-c 

非常有意思的方法，利用序列化调用覆盖 Package 里的值。妙哉

不过我有几个问题，恳请大佬解答

1. 
   > hotpatch重命名ZUPC为XPUC
   
   这里的 `ZUPC` 指的是 `GUPC`?

   `XPUC` 指的是 `XUPC`?

1. 有考虑过其他操作系统的兼容性吗？比如在 `_UPC` 通过 `If (_OSI("Darwin")){}` 判断并返回被重命名的 `XUPC()`

1. 重写的 `GUPC` 收了一个参数，调用的时候也给了一个 One，但是我没看出来这个参数的用途，新的函数里也没使用过 `Arg0`

1. 
   > 然后任一端口的_UPC Method均调用序列化GUPC方法

   据我所知，每个接口都有个 ` _UPC` 方法，任意端口放一个等于是只调用了一次？

**Comment by Teacher-c** [comment]
@williambj1
1. 是的，笔误。应该是hotpatch重命名GUPC为XUPC
2.当然可以，这一点很简单。
3.我只是举了一个调用的例子而已，这个参数是Zero还是One在原始的ssdt调用GUPC方法的时候已经写好，对应着USB端口是否启用。但是我们可以拦截改写。Arg0是可以不用，我只是偷懒，因为我的本机SSDT里关于USB端口是否启用的配置都是正确的，所以用传入的Arg0做判断而已。另外我自己屏蔽了HS04端口。
4.根据我在自己的电脑的测试，确实是这样的。

**Comment by Teacher-c** [comment]
@williambj1 
考虑操作系统的兼容性的话可以这样处理：
```Swift
        Name (USBP, Zero)
        Method (GUPC, 1, Serialized)
        {
            If (_OSI ("Darwin"))
            {
                Name (PCKG, Package (0x04)
                {
                    0xFF, 
                    0x03, 
                    Zero, 
                    Zero
                })
                USBP += One
                If (((USBP == 0x04) || (Arg0 == Zero)))
                {
                    PCKG [Zero] = Zero
                }

                If ((((USBP == 0x04) || (USBP == 0x05)) || (USBP == 0x06)))
                {
                    PCKG [One] = 0xFF
                }

                Return (PCKG) 
            }
            Else
            {
                Local0 = XUPC (Arg0)
                Return (Local0)
            }
        }
```

**Comment by athlonreg** [comment]
能否上传一份啰嗦模式下开机时的日志看一下有没有相关的ACPI报错呢

**Comment by Teacher-c** [comment]
@athlonreg 我早已反复确认过了，不存在acpi错误

**Comment by GZXiaoBai** [comment]
已经将本方法具体写为教程了，链接如下
[https://blog.gzxiaobai.cn/post/利用GUPC以热补丁定制USB端口](https://blog.gzxiaobai.cn/post/利用GUPC以热补丁定制USB端口)

**Comment by athlonreg** [comment]
[issue18](https://github.com/daliansky/OC-little/issues/18#issuecomment-846516302)
