### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [daliansky/OC-little#19]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by williambj1** [comment]
Use other sources for personal issue support
