### ISSUE TITLE
请求：能不能把我的电池教程(博客)加上

### ISSUE THREAD

**Issue by GZXiaoBai** [daliansky/OC-little#20]
我是GZ小白，我也想提供一下我的**电池教程**和**博客**
**Coding**：[http://yqp7js.coding-pages.com/2020/05/16/为小白设计的电池教程（DSDT）/](http://yqp7js.coding-pages.com/2020/05/16/为小白设计的电池教程（DSDT）/)
[http://yqp7js.coding-pages.com/2020/05/16/进阶：电池热补丁（Battery-Hotpatch）之路/](http://yqp7js.coding-pages.com/2020/05/16/进阶：电池热补丁（Battery-Hotpatch）之路/)
**Github**:[https://gzxiaobai.github.io](https://gzxiaobai.github.io)
我的补丁库在电池补丁那里已经收录了，希望教程也能收录一些，谢谢！

**Comment by athlonreg** [comment]
已添加 hotpatch 部分链接，谢谢
