### ISSUE TITLE
About battery hotpatch guide

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/OC-little#22]
Can someone help me with battry patch according to new guide : https://xstar-dev.github.io/hackintosh_advanced/Guide_For_Battery_Hotpatch.html#如何排查错误 ?

I cannot find any way to download the ssdt from baidu and guide seems laso to difficult for me.

My problem is that my battery percentage is 5-6% off (compared to coconut battery and windows).

Here is my dsdt if anyone can help (seems I havea BAT0 and a BAT1 , but my laptop has only 1 battery installed).
[System DSDT.aml.zip](https://github.com/daliansky/OC-little/files/4742561/System.DSDT.aml.zip)

Thanks in advance.

**Comment by williambj1** [comment]
You can do it without the sample, the written guide has included almost every case.

If the guide is too difficult, it’s certainly not the writer’s fault, this place is not a personal helping center so I’d suggest you to go to dedicated places to do so.
