### ISSUE TITLE
关于02-04仿冒环境光传感器中已存在ALSD环境光传感器情况

### ISSUE THREAD

**Issue by szhifei** [daliansky/OC-little#26]
这里给出的SSDT-ALSD默认了ALSD设备在_SB下，但有的电脑的ALSD设备在\下，希望可以更新一下文档，分两种情况。改成这样即可，虽然区别不大
DefinitionBlock ("", "SSDT", 2, "OCLT", "ALSD", 0)
{
    External (ALSE, IntObj)

    Scope (\)
    {
        If (_OSI ("Darwin"))
        {
            Store (0x02, ALSE)
        }
    }
}
或
DefinitionBlock ("", "SSDT", 2, "OCLT", "ALSD", 0)
{
    External (ALSE, IntObj)

    Scope (_SB)
    {
        If (_OSI ("Darwin"))
        {
            Store (0x02, ALSE)
        }
    }
}

**Comment by athlonreg** [comment]
> 这里给出的SSDT-ALSD默认了ALSD设备在_SB下，但有的电脑的ALSD设备在\下，希望可以更新一下文档，分两种情况。改成这样即可，虽然区别不大
> DefinitionBlock ("", "SSDT", 2, "OCLT", "ALSD", 0)
> {
> External (ALSE, IntObj)
> 
> ```
> Scope (\)
> {
>     If (_OSI ("Darwin"))
>     {
>         Store (0x02, ALSE)
>     }
> }
> ```
> 
> }
> 或
> DefinitionBlock ("", "SSDT", 2, "OCLT", "ALSD", 0)
> {
> External (ALSE, IntObj)
> 
> ```
> Scope (_SB)
> {
>     If (_OSI ("Darwin"))
>     {
>         Store (0x02, ALSE)
>     }
> }
> ```
> 
> }

有相应的案例吗，可否提供一下 ALSD 设备在 \ 下的截图

**Comment by szhifei** [comment]
<img width="960" alt="ALSD" src="https://user-images.githubusercontent.com/56639945/88609185-17320200-d0b6-11ea-93ce-30a4c62d71e1.png">
机型是戴尔的ins15-7577

**Comment by williambj1** [comment]
能麻烦上传完整 ACPI 表吗，得确认一下 `ALSE` 是怎么创建的

**Comment by szhifei** [comment]
[DSDT.zip](https://github.com/daliansky/OC-little/files/4985634/DSDT.zip)
别的我也不太懂，但我使用`Scope(_SB)`确实开不了机，改成`Scope(\)`就能开机了，IORegistryExplorer也能看到ALSD设备

**Comment by athlonreg** [comment]
> [DSDT.zip](https://github.com/daliansky/OC-little/files/4985634/DSDT.zip)
> 别的我也不太懂，但我使用`Scope(_SB)`确实开不了机，改成`Scope(\)`就能开机了，IORegistryExplorer也能看到ALSD设备

刚看了一下，应该是原始ACPI存在_SB._INI造成了冲突，这种情况不能在_INI下进行预置变量。

**Comment by athlonreg** [comment]
![](https://cdn.jsdelivr.net/gh/tlhub/1/20200728135259.png)

如图，注意事项里面已经有了说明！
