### ISSUE TITLE
PTSWAK - DGPU 操作相关疑问

### ISSUE THREAD

**Issue by SukkaW** [daliansky/OC-little#33]
1. `DGPU` 对象的 `ON` 和 `OFF` 方法

`DGPU` 下的方法是在屏蔽独显 SSDT 中定义的。虽然添加了 `CodeRefOf`，但是仍然显得冗余。

2. 关于在 PTSWAK 过程中操作 `DGPU` 的必要性

在 `PTSWAK` 期间操作独显 [源于 Rehabman 的 Clover HotPatch](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PTSWAK.dsl)，在 Rehabman 的 `SSDT-RMCF` 中也没有说明其必要性，且此值默认为 `0` （禁用）。

私以为，操作 `DGPU` 应该作为可选的 EXT 插件实现。

**Comment by athlonreg** [comment]
> 1. `DGPU` 对象的 `ON` 和 `OFF` 方法
> 
> `DGPU` 下的方法是在屏蔽独显 SSDT 中定义的。虽然添加了 `CodeRefOf`，但是仍然显得冗余。
> 
> 1. 关于在 PTSWAK 过程中操作 `DGPU` 的必要性
> 
> 在 `PTSWAK` 期间操作独显 [源于 Rehabman 的 Clover HotPatch](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PTSWAK.dsl)，在 Rehabman 的 `SSDT-RMCF` 中也没有说明其必要性，且此值默认为 `0` （禁用）。
> 
> 私以为，操作 `DGPU` 应该作为可选的 EXT 插件实现。

在10.13时屏蔽独显参数失效，RehabMan为此写了一篇[禁用独显的帖子](https://www.tonymacx86.com/threads/fix-window-server-service-only-ran-for-0-seconds-with-dual-gpu.233092/)，其中直接对独显设备的OFF方法进行了调用，在多台机器测试时也发现这种方法挺稳，个人觉得其实单纯用于禁止独显的话独立出来一个SSDT调用OFF方法没什么问题，比如直接定义一个设备CTD1，设备内部定义_INI方法去调用独显设备的_OFF方法
