### ISSUE TITLE
使用IRQ补丁，在睡眠之后时间为睡眠前的时间，RTC没有工作

### ISSUE THREAD

**Issue by franksfc** [daliansky/OC-little#34]
使用IRQ补丁在睡眠之后时间为睡眠前的时间，RTC没有工作。刚刚换到opencore引导，原来可以勾选clover的hpet修补，否则开不了机；在clover再使用SSDT-RTC_Y-AWAC_N的补丁就可以解决了。opencore下有什么办法？

**Comment by athlonreg** [comment]
仿冒设备时需注意设备内容需与原设备一致，否则会出现睡眠期间时间暂停的问题
