### ISSUE TITLE
使用0D/6D补丁睡眠后关机黑屏无法断电

### ISSUE THREAD

**Issue by panxiuwen** [daliansky/OC-little#37]
个人觉得是bios和电源管理的锅
1.型号是傻多戴的灵越3543，bios是最新版
2.使用了SSDT-GPRW补丁，电脑才能正常睡眠不被网卡唤醒
3.重置bios后如果不睡眠一样可以关机，但睡眠后不重置bios就不能关机
4.使用opencore引导系统，0.61和0.62都试过，是一样的问题
5.使用了安装mojava和catlina也是这个问题

**Comment by xjn819** [comment]
> 个人觉得是bios和电源管理的锅
> 1.型号是傻多戴的灵越3543，bios是最新版
> 2.使用了SSDT-GPRW补丁，电脑才能正常睡眠不被网卡唤醒
> 3.重置bios后如果不睡眠一样可以关机，但睡眠后不重置bios就不能关机
> 4.使用opencore引导系统，0.61和0.62都试过，是一样的问题
> 5.使用了安装mojava和catlina也是这个问题

参考CMOS相关以及FadtEnableReset，这与0D/6D本身无关。
