### ISSUE TITLE
ACPIDebug - maybe something is missing

### ISSUE THREAD

**Issue by antoniomcr96** [daliansky/OC-little#39]
I followed your guide inside ACPIDebug. 
I put "ACPIDebug.kext", that is correctly running:
`antonio@MacBook-Pro ~ % sudo kextstat -l|grep rehab                                   
Executing: /usr/bin/kmutil showloaded --list-only
   71    0 0                  0xa000     0xa000     com.rehabman.driver.ACPIDebug (0.1.4) 9A0916D1-E9C6-3570-90E9-4DDC4BB19FB7 <13 5 3>`
I created a custom SSDT for almost every EC Query in my DSDT (lost hours...):
```
DefinitionBlock ("", "SSDT", 2, "REMAP", "_KBD", 0x00000000)
{
    External (_SB_.PCI0.LPCB.H_EC, DeviceObj)
    External (RMDT.PUSH, MethodObj)   

    Scope (\_SB.PCI0.LPCB.H_EC)
    {
        Method (_Q50, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
        {
            \RMDT.PUSH ("Q50")
        }

        Method (_Q51, 0, NotSerialized)  
        {
            \RMDT.PUSH ("Q51")
        }

        Method (_Q6C, 0, NotSerialized)
        {
            \RMDT.PUSH ("Q6C")
        }

and so on...
```
I made and applied all the rename patches on config.plist.
ACPI table correctly loads but I don't have any sign of life of the EC Queries when I press a key in my log.

Your guide is the only found online that uses custom SSDT to make ACPIDebug work.
Maybe I'm missing something from your folder or maybe there is some operation that is not reported. I hope this reporting could be useful in case something is missing. Sorry if it's my mistake but I can't find other solutions at the moment and I think I did all that was described (helping with google translate).

Thanks in advance
System: Big Sur Beta 9

EDIT: tried to patch DSDT directly with patches by RehabMan. DSDT correctly loaded, with RMDT.PUSH for every EC Query. I don't have any log, though. Maybe the kext doesn't work with Big Sur?

**Comment by Xiashangning** [comment]
I have also experienced the same thing! However, I found the output during the verbose boot among other outputs like Lilu (DBG)... [IGPU]... something like that. But when I entered the system, ACPIDebug seems to cease functioning. I cannot find its output anywhere. Maybe that is because Big Sur changes some behaviors?

**Comment by the-eric-kwok** [comment]
Call RMDT like `\RMDT.PUSH ("[RMDT] Q6C")`, and then try to get log with command `log show --last boot | grep 'RMDT'` in terminal.
