### ISSUE TITLE
23-HPET_RTC_TIMR三合一补丁 为何不直接重新分配 IRQ 呢

### ISSUE THREAD

**Issue by hereisderek** [daliansky/OC-little#4]
直接删除 TIMR, RTC  的 IRQ, 或者找个空闲的填上 然后手动指定 HEPT 设备的 irq 感觉更方便

**Comment by athlonreg** [comment]
> 直接删除 TIMR, RTC 的 IRQ, 或者找个空闲的填上 然后手动指定 HEPT 设备的 irq 感觉更方便

oc部件要求一套acpi统一用在所有操作系统，为了安全和通用性要求，才制作此补丁，任何要求acpi的十六进制更名和未做安全处理的方法本项目均不采用。
