### ISSUE TITLE
SSDT-PNLF-ACPI on HP 630 CPU Arrandale 

### ISSUE THREAD

**Issue by Baio1977** [daliansky/OC-little#41]
Hi I have a problem with the PNLF configuration on this HW, well the problem is quite known and I would like to fix it once and for all if possible, maybe with your help
I leave ACPI origin, SSDT Hack and ioreg below, EVERYTHING works, only PNLF is missing I see the control bar, FN keys work but the brightness adjustment has NO effect

[HP 630 OC 0.6.5.zip](https://github.com/daliansky/OC-little/files/5738867/HP.630.OC.0.6.5.zip)

[HP 630 CPU Arrandale SSDT Hack.zip](https://github.com/daliansky/OC-little/files/5738862/HP.630.CPU.Arrandale.SSDT.Hack.zip)

[DSDT.zip](https://github.com/daliansky/OC-little/files/5738864/DSDT.zip)

**Comment by williambj1** [comment]
Sorry but this repo is only for storing tutorials, please use other sources for personal help.
