### ISSUE TITLE
07-PS2键盘映射及亮度快捷键，执行“ioio -s ApplePS2Keyboard LogScanCodes 1”提示：“No service matching "ApplePS2Keyboard"”

### ISSUE THREAD

**Issue by i7soft** [daliansky/OC-little#46]
直接修改：
修改 VoodooPS2Keyboard.kext\info\IOKitPersonalities\Platform Profile\Default\LogScanCodes = 1

在控制台也搜不到跟“ ApplePS2Keyboard”有关的内容

**Comment by Jonny-china** [comment]
我也遇到同样的问题，控制台打印不出

**Comment by i7soft** [comment]
我知道为啥了，big sur 不行，之前的版本可以，我有两个系统，进另外的旧系统就可以了
